//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacketViewerLogViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 64, 0")]
        public global::System.Drawing.Color ColFontIN {
            get {
                return ((global::System.Drawing.Color)(this["ColFontIN"]));
            }
            set {
                this["ColFontIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 255, 238")]
        public global::System.Drawing.Color ColBackIN {
            get {
                return ((global::System.Drawing.Color)(this["ColBackIN"]));
            }
            set {
                this["ColBackIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 255, 204")]
        public global::System.Drawing.Color ColSyncIN {
            get {
                return ((global::System.Drawing.Color)(this["ColSyncIN"]));
            }
            set {
                this["ColSyncIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 128, 64")]
        public global::System.Drawing.Color ColSelectIN {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectIN"]));
            }
            set {
                this["ColSelectIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 32, 0")]
        public global::System.Drawing.Color ColBarIN {
            get {
                return ((global::System.Drawing.Color)(this["ColBarIN"]));
            }
            set {
                this["ColBarIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 64")]
        public global::System.Drawing.Color ColFontOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColFontOUT"]));
            }
            set {
                this["ColFontOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 238, 255")]
        public global::System.Drawing.Color ColBackOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColBackOUT"]));
            }
            set {
                this["ColBackOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204, 204, 255")]
        public global::System.Drawing.Color ColSyncOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColSyncOUT"]));
            }
            set {
                this["ColSyncOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 64, 128")]
        public global::System.Drawing.Color ColSelectOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectOUT"]));
            }
            set {
                this["ColSelectOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 32")]
        public global::System.Drawing.Color ColBarOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColBarOUT"]));
            }
            set {
                this["ColBarOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 32, 32")]
        public global::System.Drawing.Color ColFontUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColFontUNK"]));
            }
            set {
                this["ColFontUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColBackUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColBackUNK"]));
            }
            set {
                this["ColBackUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 238, 238")]
        public global::System.Drawing.Color ColSyncUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColSyncUNK"]));
            }
            set {
                this["ColSyncUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 32, 32")]
        public global::System.Drawing.Color ColSelectUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectUNK"]));
            }
            set {
                this["ColSelectUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColBarUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColBarUNK"]));
            }
            set {
                this["ColBarUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 255, 238")]
        public global::System.Drawing.Color ColSelectedFontIN {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectedFontIN"]));
            }
            set {
                this["ColSelectedFontIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 238, 255")]
        public global::System.Drawing.Color ColSelectedFontOUT {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectedFontOUT"]));
            }
            set {
                this["ColSelectedFontOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColSelectedFontUNK {
            get {
                return ((global::System.Drawing.Color)(this["ColSelectedFontUNK"]));
            }
            set {
                this["ColSelectedFontUNK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExternalParseEditor {
            get {
                return ((bool)(this["ExternalParseEditor"]));
            }
            set {
                this["ExternalParseEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AutoLoadVideo {
            get {
                return ((int)(this["AutoLoadVideo"]));
            }
            set {
                this["AutoLoadVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoOpenVideoForm {
            get {
                return ((bool)(this["AutoOpenVideoForm"]));
            }
            set {
                this["AutoOpenVideoForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte PacketListStyle {
            get {
                return ((byte)(this["PacketListStyle"]));
            }
            set {
                this["PacketListStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreParseData {
            get {
                return ((bool)(this["PreParseData"]));
            }
            set {
                this["PreParseData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int ColFieldCount {
            get {
                return ((int)(this["ColFieldCount"]));
            }
            set {
                this["ColFieldCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chocolate")]
        public global::System.Drawing.Color ColField1 {
            get {
                return ((global::System.Drawing.Color)(this["ColField1"]));
            }
            set {
                this["ColField1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumSeaGreen")]
        public global::System.Drawing.Color ColField2 {
            get {
                return ((global::System.Drawing.Color)(this["ColField2"]));
            }
            set {
                this["ColField2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CornflowerBlue")]
        public global::System.Drawing.Color ColField3 {
            get {
                return ((global::System.Drawing.Color)(this["ColField3"]));
            }
            set {
                this["ColField3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkSalmon")]
        public global::System.Drawing.Color ColField4 {
            get {
                return ((global::System.Drawing.Color)(this["ColField4"]));
            }
            set {
                this["ColField4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color ColField5 {
            get {
                return ((global::System.Drawing.Color)(this["ColField5"]));
            }
            set {
                this["ColField5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Brown")]
        public global::System.Drawing.Color ColField6 {
            get {
                return ((global::System.Drawing.Color)(this["ColField6"]));
            }
            set {
                this["ColField6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MidnightBlue")]
        public global::System.Drawing.Color ColField7 {
            get {
                return ((global::System.Drawing.Color)(this["ColField7"]));
            }
            set {
                this["ColField7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ColField8 {
            get {
                return ((global::System.Drawing.Color)(this["ColField8"]));
            }
            set {
                this["ColField8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color ColField9 {
            get {
                return ((global::System.Drawing.Color)(this["ColField9"]));
            }
            set {
                this["ColField9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColField10 {
            get {
                return ((global::System.Drawing.Color)(this["ColField10"]));
            }
            set {
                this["ColField10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color ColField11 {
            get {
                return ((global::System.Drawing.Color)(this["ColField11"]));
            }
            set {
                this["ColField11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Maroon")]
        public global::System.Drawing.Color ColField12 {
            get {
                return ((global::System.Drawing.Color)(this["ColField12"]));
            }
            set {
                this["ColField12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Navy")]
        public global::System.Drawing.Color ColField13 {
            get {
                return ((global::System.Drawing.Color)(this["ColField13"]));
            }
            set {
                this["ColField13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Violet")]
        public global::System.Drawing.Color ColField14 {
            get {
                return ((global::System.Drawing.Color)(this["ColField14"]));
            }
            set {
                this["ColField14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Turquoise")]
        public global::System.Drawing.Color ColField15 {
            get {
                return ((global::System.Drawing.Color)(this["ColField15"]));
            }
            set {
                this["ColField15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Setting {
            get {
                return ((global::System.Drawing.Color)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
